AB#8758 Components serialization
Sitecore/Sitecore.Demo.XmCloud.PlaySummit pull request #76
Opened 2023-05-18 13:24 UTC by sc-nelikostadinova

2023-05-24 20:09 UTC, adoprog commented
It would be good to also add some guidance on how to use them to README.md

2023-06-12 14:40 UTC, jflheureux requested changes
I reviewed this PR locally while using the feature/8774-sitecore-components branch (with all the new serialized files)

2023-06-12 14:40 UTC, jflheureux commented on componentspush.ps1
> +      Invoke-WebRequest -Uri $componentUrl -Method Post -Body ($component | ConvertTo-Json -depth 100) -Headers $headers -ContentType "application/json"
@adoprog I am getting errors when pushing serialized components to a new XM Cloud organization. Specifically if the serialized content contains collections that do not exist on the new XM Cloud organization:
```
Collection:  Static Components
  Component:  Promo
Invoke-WebRequest : {"statusCode":404,"error":"Not Found","message":"Could not find collection"}
At C:\projects\Sitecore.Demo.XmCloud.PlaySummit\componentspush.ps1:23 char:7
+       Invoke-WebRequest -Uri $componentUrl -Method Post -Body ($compo ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
    Version:  Name ( staged )
```

We should create the collections first if they do not already exist.

2023-06-13 06:03 UTC, sc-nelikostadinova commented on docs/website.md
> +.\componentspush.ps1 -libraryId _your_library_id_ -apiKey _your_api_key_
Will there be a better way to get that or should we explain the way to get it from the network tab? I felt like this was a temporary solution but I could be wrong.

2023-06-13 10:40 UTC, jflheureux commented on docs/website.md
> +.\componentspush.ps1 -libraryId _your_library_id_ -apiKey _your_api_key_
I do not know. We should ask Hande Bodart. Do you want to ask her or do you want me to ask?

2023-07-06 11:40 UTC, sc-nelikostadinova commented
Closing because the fix for collections is in here: https://github.com/Sitecore/Sitecore.Demo.XmCloud.PlaySummit/pull/85

2023-07-06 11:40 UTC, closed without merging