AB#8774 Sitecore Components
Sitecore/Sitecore.Demo.XmCloud.PlaySummit pull request #85
Opened 2023-07-06 11:35 UTC by sc-nelikostadinova

2023-07-06 20:28 UTC, jflheureux requested changes

2023-07-07 11:31 UTC, sc-nelikostadinova commented on src/components/components/NIgQ4zdtlQ.json
This is expected. I had to create two dark themes because of the different elements that are being used so that there is no additional adjustments required from the SEs. High contrast theme works well on components with cards in them. Dark theme doesn't look great on the Sponsor promo because of the logos we have.

2023-07-07 11:32 UTC, sc-nelikostadinova commented on src/components/components/EJIWSdccwi.json
That's currently not possible

2023-07-07 11:33 UTC, sc-nelikostadinova commented on src/components/components/EJIWSdccwi.json
I am not sure about this, I feel like it was mentioned in our previous conversations with them regarding the "articles" section that we had in mind in the beginning.

2023-07-07 14:36 UTC, sc-nelikostadinova commented on src/components/components/KzEssOTo6j.json
Should be fixed now, it was a product issue

2023-07-18 18:32 UTC, jflheureux commented on src/components/components/NIgQ4zdtlQ.json
Thanks. This will have to be mentioned in the demo scenarios we will write once the Components are merged and usable by demo users.

2023-07-18 19:28 UTC, jflheureux commented on src/components/components/NIgQ4zdtlQ.json
When I look at the serialized components files, I still see many `"name:  "Name"` components. All of them have a "draft", "staged" or "saved" status. The "published" statuses are having the modified names. The modified names are also displayed in Pages. It only looks weird in the terminal when pulling/pushing:
![image](https://github.com/Sitecore/Sitecore.Demo.XmCloud.PlaySummit/assets/2000200/ab3db82d-d505-421c-a199-1d17e2d7acd0)

Do you think this could be fixed?

2023-07-21 14:13 UTC, jflheureux requested changes

2023-07-21 14:13 UTC, jflheureux commented on src/components/styles.json
On a new XM Cloud project, if I do the following actions:
1. Push
2. Pull

I end up with a modified styles.json file with that change.
![image](https://github.com/Sitecore/Sitecore.Demo.XmCloud.PlaySummit/assets/2000200/7c25abff-fa57-4e93-8105-fad3a4447502)

What is the right value to commit here? Could you look at that?

2023-07-21 14:13 UTC, jflheureux commented on src/components/components/NIgQ4zdtlQ.json
I renamed all the "Name" versions to their correct names.

2023-07-21 14:33 UTC, jflheureux commented on src/components/collections.json
After pushing the components into a new Sitecore Components library (from a new XM Cloud project), the components were not available to be used in Pages. I created an issue in Teams. See the comment in work item 8774 for the Teams link.

We must resolve this before merging the PR.

2023-07-21 15:28 UTC, jflheureux commented on src/components/collections.json
Fixed by https://github.com/Sitecore/Sitecore.Demo.XmCloud.PlaySummit/pull/85/commits/5ee1db779f5fe9e9390813f7f4d383f7284bc9b5

2023-07-25 11:15 UTC, chpa7 approved these changes

2023-07-25 11:22 UTC, merged